# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-31 21:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='height_field',
            new_name='visits',
        ),
        migrations.RemoveField(
            model_name='post',
            name='width_field',
        ),
    ]
