# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-17 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribers',
            name='confirmKey',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
